# Configuración de GitHub Actions para URL Automation
# ===================================================

# Configuración del sistema de URLs automáticas para GitHub Actions
GITHUB_ACTIONS_CONFIG = {
    # Intervalo de ejecución (en minutos)
    "check_interval_minutes": 5,
    
    # Configuración de commits automáticos
    "auto_commit": True,
    "auto_push": True,
    "commit_author_name": "Cloudflare URL Auto-Update",
    "commit_author_email": "action@github.com",
    
    # Configuración de notificaciones
    "notifications_enabled": True,
    "slack_notifications": False,  # Cambiar a True y agregar SLACK_WEBHOOK_URL a secrets
    "discord_notifications": False,  # Cambiar a True y agregar DISCORD_WEBHOOK_URL a secrets
    
    # Configuración de validación
    "validate_new_url": True,
    "validation_timeout": 30,
    "max_retries": 3,
    
    # Configuración de archivos
    "backup_enabled": True,
    "exclude_files": [
        ".git/*",
        "node_modules/*",
        "__pycache__/*",
        "*.pyc",
        ".github/workflows/*"  # No tocar otros workflows
    ]
}

# URLs de endpoints críticos
CRITICAL_ENDPOINTS = [
    "/health",
    "/cf_url", 
    "/data"
]

# Configuración de monitoreo
MONITORING_CONFIG = {
    "health_check_timeout": 15,
    "max_consecutive_failures": 3,
    "fallback_urls_minimum": 2
}

# Plantillas de mensajes
COMMIT_MESSAGE_TEMPLATE = """🔄 Auto-update Cloudflare URL to {new_url}

- Detected URL change via automated monitoring
- Updated all references automatically  
- Previous URL: {old_url}
- New URL: {new_url}
- Files updated: {files_count}
- Triggered at {timestamp}
- Auto-generated by GitHub Actions

[skip ci] # Skip CI para evitar loops infinitos"""

NOTIFICATION_MESSAGE_TEMPLATE = """🔄 **Cloudflare URL Update**

📊 **Summary:**
• Previous URL: `{old_url}`
• New URL: `{new_url}`
• Files updated: {files_count}
• Timestamp: {timestamp}

✅ All systems updated automatically
🚀 Streamlit Cloud will redeploy automatically"""

# Configuración de seguridad
SECURITY_CONFIG = {
    "validate_url_format": True,
    "allowed_domains": [
        "trycloudflare.com",
        "ngrok.io",  # Si decides usar ngrok en el futuro
        # Agregar otros dominios permitidos aquí
    ],
    "require_https": True,
    "check_ssl_cert": False  # Cloudflare tunnels usan certificados dinámicos
}