# Configuración OPTIMIZADA para Streamlit Cloud
# ===============================================

[server]
# Configuración del servidor para cloud
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[browser]
# No abrir navegador automáticamente en cloud
gatherUsageStats = false

[theme]
# Tema optimizado
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[runner]
# Optimizaciones de rendimiento para cloud
magicEnabled = true

[client]
# Configuración del cliente
showErrorDetails = true
toolbarMode = "minimal"

# Sin configuraciones obsoletas que causan warnings
# Removido installTracer, fixMatplotlib, logLevel que ya no son válidas
