# Streamlit Cloud Secrets Template
# Copy these to your Streamlit Cloud app secrets

[secrets]
# Groq API Key (REQUIRED) - 100% GRATIS
# Get your FREE API key from: https://console.groq.com/
GROQ_API_KEY = "gsk_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Jetson API URL (OPTIONAL - uses default if not provided)
# Replace with your actual Jetson API URL
JETSON_API_URL = "https://dpi-opportunity-hybrid-manufacturer.trycloudflare.com"

# Additional optional secrets
ENVIRONMENT = "production"
DEBUG_MODE = false
LOG_LEVEL = "INFO"
