# Streamlit Cloud Secrets Template
# Copy these to your Streamlit Cloud app secrets

[secrets]
# HuggingFace API Token (REQUIRED)
# Get your token from: https://huggingface.co/settings/tokens
HUGGINGFACE_API_TOKEN = "hf_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Jetson API URL (OPTIONAL - uses default if not provided)
# Replace with your actual Jetson API URL
JETSON_API_URL = "https://dpi-opportunity-hybrid-manufacturer.trycloudflare.com"

# Additional optional secrets
ENVIRONMENT = "production"
DEBUG_MODE = false
LOG_LEVEL = "INFO"
